sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=lint
  - python: 3.5.3
    env: TOXENV=pylint
  - python: 3.5.3
    env: TOXENV=cov
    after_success: coveralls
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
  - python: 3.8-dev
    env: TOXENV=py38
    dist: xenial
    if: branch = dev AND type = push
  allow_failures:
  - python: 3.8-dev
    env: TOXENV=py38
    dist: xenial
cache:
  directories:
  - "$HOME/.cache/pip"
install: pip install -U tox coveralls
language: python
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  user: kstaniek
  password:
    secure: R4i/AF1sOmbcteumKnS1/mhrgqJAqdiAL9A9VSq1Fm4FiBVCyOv33D6nJD2/8WAyQnNITO8JEWtdmfyyTovHOHb9lWO4Rt6OdDuvW46kL9iN1KU3HXO8E25pV+9fmzcJXgwwIqobJJvbVDQbOVWR/4fciYoQJ0ckoxSpnlos4+vr0SC4x8Ic0tV+9AP7+3XbLVHqXlasHRaTxMDXULCUbG2ywVWpFJG/7JDuhnY/nHIN/bSi+K0KPZ/hF9X4waCJiNztE0R07CnlBJAgFWAZlEFRVhJbQqXMoOXdEgXbJxdIqLRm37fuOs7cNKviVYD96kVu4vhxAiV0fF9o+q+RciALInZYrY1yUVHUoIqehwMe8KNSY6n0UqQxiicPRdENhXlxaSsGEyjZmK1nt92Yk2NdnkmbLA3xxFfwJZemN5yWl7v78521SuhIOUUlAeSPu8prvdO7m8GrERvYiST4OcMea9w13zisKfSVHeiwbrI+ZzbZ853/b1trfibBj2c4NGLNNBxJOePBZXNHSGtJTYQhnF23FR7GyzkD0unwXwlgRgKRp4CZFEkZThfJsp0dHV/hIA84Jtrq8W81tn+JcISNwlhOIMUbxr4Hlj9bRAer72Gf64L3VWjSp3imYLYbe9h50Cp+iM3MK0UsZ117J1421AZC4c0zzjsk+76wS2E=
